### ISSUE TITLE
I'm giving this library away

### ISSUE THREAD

**Issue by neongreen** [vrom911/shortcut-links#7]
Write here if you want to take over.

**Comment by vrom911** [comment]
Hey there! As @kowainik is using this library for `hakyll-shortcut-links` we could take care of this package. Let us know what you think.

**Comment by neongreen** [comment]
Ok, I need repository creating permissions in `@kowainik` to transfer the repo to you.

**Comment by vrom911** [comment]
You can transfer it to my account, I do have rights to transfer it to @kowainik :slightly_smiling_face:

**Comment by neongreen** [comment]
Done for shortcut-links and ilist.

**Comment by neongreen** [comment]
And you have maintainer rights on Hackage, too.

**Comment by vrom911** [comment]
Received, thank you very much! :+1:
